#ifndef __AECONVPARA_H__
#define __AECONVPARA_H__

#define SIGNAL_DIM "SIGNAL_DIM"
#define SIGNAL_WIDTH "SIGNAL_WIDTH"
#define SIGNAL_HEIGHT "SIGNAL_HEIGHT"
#define SIGNAL_CHANNELS "SIGNAL_CHANNELS"

#define LAYERS "LAYERS"
#define LAYER_NAME "LAYER_NAME"
#define LAYER_INPUT_CHANNELS "LAYER_INPUT_CHANNELS"
#define LAYER_OUTPUT_CHANNELS "LAYER_OUTPUT_CHANNELS"
#define LAYER_COEFFS "LAYER_COEFFS"
#define LAYER_BIASE "LAYER_BIASE"
#define LAYER_TRANS_TPYE "LAYER_TRANS_TYPE"
#define LAYER_POOL_TPYE "LAYER_POOL_TYPE"
#define LAYER_PATCH_WIDTH "LAYER_PATCH_WIDTH"
#define LAYER_PATCH_HEIGHT "LAYER_PATCH_HEIGHT"
#define LAYER_STEP_WIDTH "LAYER_STEP_WIDTH"
#define LAYER_STEP_HEIGHT "LAYER_STEP_HEIGHT"
#define LAYER_KERNEL_WIDTH "LAYER_KERNEL_WIDTH"
#define LAYER_KERNEL_HEIGHT "LAYER_KERNEL_HEIGHT"
#define LAYER_PREV_FEATURE_MAP_COUNT "LAYER_PREV_FEATURE_MAP_COUNT"
#define LAYER_CUR_FEATURE_MAP_COUNT "LAYER_CUR_FEATURE_MAP_COUNT"
#define LAYER_CONCATENATE_LEFT "LAYER_CONCATENATE_LEFT"
#define LAYER_CONCATENATE_RIGHT "LAYER_CONCATENATE_RIGHT"

#endif